### ISSUE TITLE
Mobile is Floaty

### ISSUE THREAD

**Issue by zappycode** [zappycode/zappycode-django#10]
When scrolling on ZappyCode.com on mobile, it moves to the left and right. I don't like that. It should be more solid

**Comment by LordUttam** [comment]
It also moved left to right on computer if you tried to scroll it horizontally. I have tried to fix by adding in sitewide.css-
width:100%;
height:100%;
overflow-x: hidden;

**Comment by zappycode** [comment]
This was fixed in 52a7dcef357cba86855d88f54566a4736c93218e
