### ISSUE TITLE
Issue regarding the link

### ISSUE THREAD

**Issue by ShyamSundhar1411** [zappycode/zappycode-django#107]
The links are always getting redirected to python course. Just look onto it

**Comment by zappycode** [comment]
Can you share an example?

**Comment by ShyamSundhar1411** [comment]
For Eg the reactjs course is redirecting to python course when start course is clicked

**Comment by zappycode** [comment]
Oh gotcha! All fixed. Thanks for finding that

**Comment by ShyamSundhar1411** [comment]
Download button for the same is also broken

**Comment by zappycode** [comment]
Fixed :)
