### ISSUE TITLE
social buttons to share things

### ISSUE THREAD

**Issue by croolicjah** [zappycode/zappycode-django#17]
user story:
if i click the icon/button/whatever else i would have possibility to share things via socials. I want to have possibillity to change title, description, and image - as a option. 

specification:
1. ions/picuress must be fancy
2, don't want to have a lot of text
3. authorisation can be on side of user
4. with deafault values there is posibility to change the  values

**Comment by zappycode** [comment]
I like this! What would be some good places to share? The first ones that come to mind are Twitter and fb.

I wonder what we should put as the default text...I never know what to put in those haha

Also where should we put this in the page. Like I want users to be able to share but at the same time I don't want to come across as desperate for people to share

**Comment by croolicjah** [comment]
think could be linkedin as well, maybe pinterest, instagram . default text shoud depend on shared content. think there are 4 elements which should have possibility to easy share: challenges, posts, courses, and lectures whith preview
