### ISSUE TITLE
Better descriptions over the courses

### ISSUE THREAD

**Issue by Cqsi** [zappycode/zappycode-django#29]
This is just a small improvement, so I thought I might note it here in the issues section. The descriptions over the courses are alright (some more info would be cool), but I suggest making the description more readable by increasing the font size a little bit, puting more line-breaks (!) and making the headings in the Django course bigger. 

I'm not at home, so I can't change this now, but maybe somebody else can.

**Comment by zappycode** [comment]
I like this! I've also been thinking, maybe making the description a little shorter with a read more button that would expand things.
