### ISSUE TITLE
TypeError at /money

### ISSUE THREAD

**Issue by 2001asjad** [zappycode/zappycode-django#37]
**unsupported operand type(s) for +: 'NoneType' and 'NoneType' ** 
getting the above error.
I think there is an error at money/views.py line 9..
Can you please check it out.

**Comment by zappycode** [comment]
Can you share a screenshot of the full error? Also, did you migrate your DB? It also might be the case that at least one month entry has to be made in the DB first

**Comment by 2001asjad** [comment]
Yes , I migrated the DB. It says no changes detected.
I am sending the snap of the error..
![Capture](https://user-images.githubusercontent.com/60435499/91128851-8fe0aa00-e6c6-11ea-82cc-982ff5b036ac.PNG)

And here is the Code, which is the same as that I forked..
![2](https://user-images.githubusercontent.com/60435499/91129140-18f7e100-e6c7-11ea-8ba1-560d2988b8fc.PNG)
Line 9 has the error..

Please look into this issue.

Thank You

**Comment by zappycode** [comment]
Ah ok! Yes this is happening because there is no Month objects in the DB yet. You can fix this either by adding a Month object to the DB or by writing some code to not add those numbers if there are not objects. Would you like to write a fix? If so, you'd get a month free of ZappyCode!

**Comment by 2001asjad** [comment]
I Solved it to a little extent. I don't think you're gonna like it.Actually I am not able to get a right object attribute as I am a beginner.
![Capture](https://user-images.githubusercontent.com/60435499/91250527-e0174500-e776-11ea-9c92-425f2496f2ec.PNG)

and the change atleast lead me to this page than an error..
![2](https://user-images.githubusercontent.com/60435499/91250566-f6bd9c00-e776-11ea-9af8-5437fff27863.PNG)
Hey Nick! Can you please help me out with the correct change...

Please I request you for that..

Thank you sooo much..

**Comment by zappycode** [comment]
You're getting close! I would do an if statement to see if the results came back None and if so, then I would set the revenue, profit and expenses to 0

**Comment by 2001asjad** [comment]
I am sorry Nick that was  the best I could do...The if statements have already been added..
![Capture](https://user-images.githubusercontent.com/60435499/91555620-fe379d80-e94e-11ea-8329-2c12c4a1ecee.PNG)
Still that leads me to the same Money page as earlier I showed you..

Actually I can't find the correct Manager attribute to calculate the difference between 2 quantities to calculate the loss.

Can you pleaseeee help me in this Nick

**Comment by LordUttam** [comment]
The if else was to be added in the views.py!

**Comment by zappycode** [comment]
Fixed in #38 thanks to @LordUttam!
