### ISSUE TITLE
Next and Previous buttons

### ISSUE THREAD

**Issue by zappycode** [zappycode/zappycode-django#4]
When someone is watching a lecture like https://zappycode.com/courses/SwiftUI-Learn-How-to-Build-Beautiful-Robust-Apps/123/navigationlinks

There should be a next and a previous button so that students can easily navigate to the next video.

We also need to be careful so that if it's the first lecteure there is no previous button and if it's the last lecture, no next button

**Comment by amitnayal222** [comment]
I can try this.

**Comment by zappycode** [comment]
Added in 17bec2a905c984dee5b3cb8a776931ae219a6f51
