### ISSUE TITLE
Require membership for viewing courses

### ISSUE THREAD

**Issue by zappycode** [zappycode/zappycode-django#5]
Currently, anyone can watch the course. Kinda defeats the purpose of getting a membership! Haha

I want to make it so that when someone tries to watch a lecture, that it sends them to the signup page unless they are a paying member

**Comment by LordUttam** [comment]
Well I can try that but I don't know how to make dummy videos to test it locally. I created a superuser to add dummy content and then there is a 'Vimeo promo video id', 'first lecture' field which is required and opens a window with 'section' field ...
What should I do?

**Comment by zappycode** [comment]
Ya I guess we need to get https://github.com/zappycode/zappycode-django/issues/8 fixed before this one. That way there is some test data to work with
