### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by zappycode** [zappycode/zappycode-django#8]
When someone clones or downloads the project, we should have some example data ready for them like a few courses, revenue reports, a super user, and we should list these things in the tutorial

**Comment by LordUttam** [comment]
I think models.py had some problem so that while making test data, it was like course->lecture->section->course. I somehow fixed it but I am not able to go to the course landing page now.

**Comment by zappycode** [comment]
Ya I'll have to take a stab at this soon
